export const scriptureData: Record<string, string> = {
  "2 Tim. 3:16": "All Scripture is God-breathed and profitable for teaching, for conviction, for correction, for instruction in righteousness.",
  "Deut. 4:2": "You shall not add to the word which I am commanding you, nor shall you take away from it, that you may keep the commandments of Jehovah your God which I am commanding you.",
  "Deut. 12:32": "Everything that I am commanding you, you shall be careful to do; you shall not add to it nor take away from it.",
  "Prov. 30:5-6": "Every word of God is pure; He is a shield to those who take refuge in Him. Do not add to His words, lest He reprove you and you be found a liar.",
  "Rev. 22:18-19": "I testify to every one who hears the words of the prophecy of this scroll: If anyone adds to them, God will add to him the plagues which are written in this scroll; and if anyone takes away from the words of the scroll of this prophecy, God will take away his part from the tree of life and out of the holy city, which are written in this scroll.",
  "Deut. 6:4": "Hear, O Israel: Jehovah our God is one Jehovah.",
  "1 Cor. 8:4b": "There is no God but one.",
  "Isa. 45:5a": "I am Jehovah, and there is no other; besides Me there is no God.",
  "Matt. 28:19": "Go therefore and disciple all the nations, baptizing them into the name of the Father and of the Son and of the Holy Spirit.",
  "Matt. 3:16-17": "And having been baptized, Jesus went up immediately from the water, and behold, the heavens were opened to Him, and He saw the Spirit of God descending like a dove and coming upon Him. And behold, a voice out of the heavens, saying, This is My Son, the Beloved, in whom I have found My delight.",
  "2 Cor. 13:14": "The grace of the Lord Jesus Christ and the love of God and the fellowship of the Holy Spirit be with you all.",
  "John 14:10-11": "Do you not believe that I am in the Father and the Father is in Me? The words that I say to you I do not speak from Myself, but the Father who abides in Me does His works. Believe Me that I am in the Father and the Father is in Me; but if not, believe because of the works themselves.",
  "John 1:18": "No one has ever seen God; the only begotten Son, who is in the bosom of the Father, He has declared Him.",
  "John 3:16": "For God so loved the world that He gave His only begotten Son, that every one who believes into Him would not perish, but would have eternal life.",
  "John 1:1": "In the beginning was the Word, and the Word was with God, and the Word was God.",
  "John 1:14": "And the Word became flesh and tabernacled among us (and we beheld His glory, glory as of the only Begotten from the Father), full of grace and reality.",
  "Rom. 9:5": "Whose are the fathers, and out of whom, as regards what is according to flesh, is the Christ, who is over all, God blessed forever. Amen.",
  "1 Tim. 2:5": "For there is one God and one Mediator of God and men, the man Christ Jesus.",
  "1 Cor. 15:3-4": "For I delivered to you, first of all, that which also I received, that Christ died for our sins according to the Scriptures; and that He was buried, and that He has been raised on the third day according to the Scriptures.",
  "Acts 4:10": "Let it be known to all of you and to all the people of Israel that in the name of Jesus Christ the Nazarene, whom you crucified, whom God has raised from the dead, in this name this man stands before you well.",
  "Rom. 8:34": "Who is he who condemns? It is Christ Jesus who died and, rather, who was raised, who is also at the right hand of God, who also intercedes for us.",
  "Acts 5:31": "This One God has exalted to His right hand as Leader and Savior, to give repentance to Israel and forgiveness of sins.",
  "Acts 10:36": "The word which He sent to the sons of Israel, announcing the gospel of peace through Jesus Christ—this One is Lord of all.",
  "John 3:29": "He who has the bride is the bridegroom; but the friend of the bridegroom, who stands and hears him, rejoices with joy because of the bridegroom's voice. This joy of mine therefore is made full.",
  "Rev. 19:7": "Let us rejoice and exult, and let us give the glory to Him, for the marriage of the Lamb has come, and His wife has made herself ready.",
  "Rev. 11:15": "And the seventh angel trumpeted; and there were loud voices in heaven, saying, The kingdom of the world has become the kingdom of our Lord and of His Christ, and He will reign forever and ever.",
  "Rev. 19:16": "And He has on His garment and on His thigh a name written: KING OF KINGS AND LORD OF LORDS.",
  "Eph. 2:5": "Even when we were dead in offenses, made us alive together with Christ (by grace you have been saved).",
  "Eph. 2:8": "For by grace you have been saved through faith, and this not of yourselves; it is the gift of God.",
  "Rom. 3:24": "Being justified freely by His grace through the redemption which is in Christ Jesus.",
  "Rom. 3:28": "For we account that a man is justified by faith apart from the works of the law.",
  "Gal. 2:16": "And knowing that a man is not justified out of works of law but through faith in Jesus Christ, we also have believed into Christ Jesus that we might be justified out of faith in Christ and not out of works of law, because out of works of law no flesh will be justified.",
  "John 1:12-13": "But as many as received Him, to them He gave the authority to become children of God, to those who believe into His name, who were begotten not of blood, nor of the will of the flesh, nor of the will of man, but of God.",
  "Eph. 1:22-23": "And He subjected all things under His feet and gave Him to be Head over all things to the church, which is His Body, the fullness of the One who fills all in all.",
  "Rom. 12:5": "So we who are many are one Body in Christ, and individually members one of another.",
  "1 Cor. 12:12": "For even as the body is one and has many members, yet all the members of the body, being many, are one body, so also is the Christ.",
  "1 Cor. 1:2": "To the church of God which is in Corinth, to those who have been sanctified in Christ Jesus, the called saints, with all those who call upon the name of our Lord Jesus Christ in every place, who is theirs and ours.",
  "1 Thes. 1:1": "Paul and Silvanus and Timothy to the church of the Thessalonians in God the Father and the Lord Jesus Christ: Grace to you and peace.",
  "Rev. 1:11": "Saying, What you see write in a scroll and send it to the seven churches: to Ephesus and to Smyrna and to Pergamos and to Thyatira and to Sardis and to Philadelphia and to Laodicea.",
  "Rev. 21:1—22:5": "And I saw a new heaven and a new earth; for the first heaven and the first earth passed away, and the sea is no more. And I saw the holy city, New Jerusalem, coming down out of heaven from God, prepared as a bride adorned for her husband.",
  "Jude 3": "Beloved, while using all diligence to write to you concerning our common salvation, I found it necessary to write to you and exhort you to earnestly contend for the faith once for all delivered to the saints.",
  "Rom. 14:3": "He who eats, let him not despise him who does not eat; and he who does not eat, let him not judge him who eats, for God has received him.",
  "Rom. 15:7": "Therefore receive one another, as Christ also received you, to the glory of God."
};
